### ISSUE TITLE
Add command to Deployment

### ISSUE THREAD

**Issue by abhiyerra** [opszero/tiphys#19]
Command are passed:

```
apps:
  - name: payroll
    service:
      command: ["celery", "123"]
      enabled: true
      type: ClusterIP
      port: 3000
```
- [ ] Add the command if it is passed into the following line: https://github.com/opszero/tiphys/blob/main/charts/tiphys/templates/app.yaml#L68
