### ISSUE TITLE
Create an externalService component

### ISSUE THREAD

**Issue by abhiyerra** [opszero/tiphys#29]
```
apps:
  - name: sitemap
     service:
        type: ExternalName
        hosts:
          - host: yieldpayroll.com
            paths: ["/(sitemap-.*)"]
        externalName: cname.example.com
```

- [ ] Check the value of `service.type` if it is `ExternalName`, then don't create https://github.com/opszero/tiphys/blob/main/charts/tiphys/templates/app.yaml#L48
- [ ] Disable ports https://github.com/opszero/tiphys/blob/main/charts/tiphys/templates/app.yaml#L40 and add `externalName: {{ $app.service.externalName }}`
