### ISSUE TITLE
Add Nodeselector to add Karpenter selector

### ISSUE THREAD

**Issue by abhiyerra** [opszero/tiphys#33]
```
spec:
  template:
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: m5.large
```
